DATASET:
    train_list: ['Human36M']
    test_list: ['Human36M']
    input_joint_set: 'human36'
    target_joint_set: 'human36'
    workers: 16
    use_gt_input: False
    seqlen: 16
    stride: 1

MODEL:
    name: 'PoseEst'
    hpe_dim: 256
    hpe_dep: 3

TRAIN:
    print_freq: 20
    batch_size: 64
    shuffle: True
    begin_epoch: 1
    end_epoch: 60
    scheduler: 'step'
    lr: 0.00005
    lr_step: [10, 30, 50]
    lr_factor: 0.8
    optimizer: 'adam'
    wandb: True

TEST:
    batch_size: 64
    shuffle: False